language: node_js
node_js:
  - "0.12"

before_script:
  - npm run lint

script:
  - npm run test-cov

notifications:
  email:
    - jed@keystonejs.com

services:
  - mongodb

git:
  depth:
    10

cache:
  directories:
    - node_modules
